config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # 
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # 
  # resources :flats, as: 'ch' # ça me créé les 7 routes du crud
  # get /flats
  # /flats/:id
  # /flats/new
  # /flats/create
  # DELETE /flats
  # PATCH || PUT /flats/:id
  # get 'about', to: 'moncontroller#mamethodeducontroller'
  # get
  # post
  # PUT/PATH (update)
  # DELETE

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  
  def contact
    @contact = ['Benjamin', 'Arthur', 'John', 'Paul']
    @test = @contact.include?(params[:name]) ? params[:name] : 'Nothing...'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/pages/contact.html.erb
<h1>Hello from contact html erb</h1>


<ul>
  <% @contact.each do |member| %>
    <%= member %>
  <% end %>
</ul>

<form action="/contact" method="get" accept-charset="UTF-8" >
  <input id="query" name="name" type="text" />
  <input name="commit" type="submit" value="Search" data-disable-with="Search" />
</form>
<%= @test %>


<%= link_to 'le nom du lien', contact_path %>
<%= form_with %>